import java.util.Random

fun main() {
    val tree = PersonTree()
    PersonGenerator.persons(10000).
            filter { it.name.length > 22 }.forEach { tree.insert(it) }
    for( p in tree.sorted())
        println(p.nice())
}

fun Person.nice(): String {
    return "${this.name} (${phoneNo}) ${this.address.address}; ${this.address.zip} ${this.address.city}"
}


class PersonTree() {
  private companion object { // Kotlin speak for static members
      val Noone = Person("","",Address("","",""))
      val Empty = Node(Noone)
  }

  private var root : Node = Empty

  private class Node (val person: Person = Noone) {
      var left : Node = Empty
      var right: Node = Empty

      fun insert(pers: Person):Node {
        // return a Node/Tree with pers inserted
          if (this == Empty) return Node(pers)
          if (pers.name < person.name){
              left = left.insert(pers)
          } else {
              right = right.insert(pers)
          }
          return this
      }
      
      fun sorted() : Sequence<Person> = sequence {
        /* return sorted( left) + person + sorted( right)*/
          if (this@Node != Empty) { // if no @Node, this is the sequence
              yieldAll( left.sorted() )
              yield(person)
              yieldAll( right.sorted() )
          }
      }
  }


  public fun insert(pers : Person){
      root = root.insert(pers)
  }

  fun sorted() = root.sorted()

}

/**
 * The purpose of this class is is to represent contact persons
 * @author kasper
 */
data class Person(val name: String, val phoneNo: String, val address: Address)


/**
 * The purpose of this object is to generate random Person objects
 * The person() method takes as argument the number of persons to be generated
 * All persons generated will have unique phone numbers within a single call
 * to persons(), but not between two calls to persons().
 * @author kasper
 */
object PersonGenerator {


    fun persons(N: Int) = sequence(){
        for (phone in phoneNumbers(N)) {
            yield ( Person(name(), phone, AddressGenerator.address(200)) )
        }
    }

    private fun phoneNumbers(N: Int): Iterable<String> {
        if (N >10000000) throw IllegalArgumentException("Can at most make 10.000.000 phonenumbers")
        val numbers = HashSet<String>()
        while (numbers.size < N) {
            numbers.add(phoneNumber())
        }
        return numbers
    }

    private fun phoneNumber(): String {
        val rnd = Random()
        val first = rnd.nextInt(50) + 20 // from 20 to 69
        val second = rnd.nextInt(100)
        val third = rnd.nextInt(100)
        val forth = rnd.nextInt(100)
        return String.format("%02d%02d-%02d%02d", first, second, third, forth)
    }


    private fun name(): String {
        val rnd = Random()
        val first = FIRSTNAMES[rnd.nextInt(FIRSTNAMES.size)]
        val last = LASTNAMES[rnd.nextInt(LASTNAMES.size)]
        return "$first $last"
    }


}
private val LASTNAMES = arrayOf("Ahmad", "Ahmed", "Ali", "Andersen", "Andersson", "Andreasen", "Andreassen", "Andresen", "Asmussen", "Bach", "Bak",
        "Bang", "Bech", "Beck", "Bendtsen", "Berg", "Bertelsen", "Berthelsen", "Bisgård", "Bisgaard", "Bjerre", "Bjerregård",
        "Bjerregaard", "Bonde", "Brandt", "Brodersen", "Bruun", "Buch", "Bundgård", "Bundgaard", "Carlsen", "Carstensen",
        "Christensen", "Christiansen", "Christoffersen", "Clausen", "Dahl", "Dalgård", "Dalgaard", "Dalsgård", "Dalsgaard", "Dam",
        "Damgård", "Damgaard", "Danielsen", "Davidsen", "Enevoldsen", "Eriksen", "Eskildsen", "Fischer", "Frandsen", "Frederiksen",
        "Friis", "Frost", "Gade", "Gregersen", "Hald", "Hansen", "Hassan", "Hedegård", "Hedegaard", "Hemmingsen", "Henningsen",
        "Henriksen", "Hermansen", "Hjorth", "Hoffmann", "Holm", "Holst", "Hougård", "Hougaard", "Ibsen", "Iversen", "Jacobsen",
        "Jakobsen", "Jensen", "Jeppesen", "Jepsen", "Jespersen", "Jessen", "Johannesen", "Johannsen", "Johansen", "Johansson",
        "Johnsen", "Juhl", "Justesen", "Juul", "Jønsson", "Jørgensen", "Karlsen", "Khan", "Kirkegård", "Kirkegaard", "Kjeldsen",
        "Kjær", "Kjærgård", "Kjærgaard", "Klausen", "Knudsen", "Koch", "Kofoed", "Kragh", "Kristensen", "Kristiansen",
        "Kristoffersen", "Krog", "Krogh", "Kruse", "Lange", "Larsen", "Lassen", "Lauridsen", "Lauritsen", "Lauritzen", "Laursen",
        "Laustsen", "Leth", "Lind", "Lorentzen", "Lorenzen", "Lund", "Madsen", "Markussen", "Mathiasen", "Mathiesen", "Meyer",
        "Michelsen", "Mikkelsen", "Mogensen", "Mohamed", "Mortensen", "Munch", "Munk", "Müller", "Mølgård", "Mølgaard", "Møller",
        "Nguyen", "Nielsen", "Nikolajsen", "Nilsson", "Nissen", "Nygård", "Nygaard", "Nørgård", "Nørgaard", "Olesen", "Olsen",
        "Olsson", "Overgård", "Overgaard", "Paulsen", "Pedersen", "Persson", "Petersen", "Poulsen", "Rasmussen", "Ravn", "Riis",
        "Schmidt", "Schou", "Schrøder", "Schultz", "Simonsen", "Skov", "Sloth", "Sommer", "Steffensen", "Svendsen", "Svensson",
        "Søgård", "Søgaard", "Søndergård", "Søndergaard", "Sørensen", "Thomassen", "Thomsen", "Thorsen", "Thygesen", "Thøgersen",
        "Toft", "Vestergård", "Vestergaard", "Villadsen", "Vinther", "Winther", "Østergård", "Østergaard", "Ågård", "Aagård",
        "Ågaard", "Aagaard")

private val FIRSTNAMES = arrayOf("Aake", "Abdallah", "Abdel", "Abdul", "Abel", "Abraham", "Absalon", "Achim", "Achton",
        "Acton", "Adalina", "Adam", "Adane", "Adda", "Addie", "Addy", "Adea", "Adela", "Adelaide", "Adelbert", "Adele",
        "Adèle", "Adelena", "Adelfine", "Adelgunde", "Adelheid", "Adelhejd", "Adelina", "Adeline", "Adia", "Adie", "Adils",
        "Adina", "Adine", "Adolf", "Adolfe", "Adolfine", "Adolph", "Adolphine", "Adrian", "Adriana", "Adriane", "Adriano",
        "Adrienne", "Adser", "Adwan", "Agate", "Agatha", "Agathe", "Agda", "Agga", "Agge", "Aggi", "Agna", "Agnar", "Agne",
        "Agner", "Agnes", "Agnès", "Agneta", "Agnete", "Agnetha", "Agnethe", "Agny", "Ahmed", "Ahrendt", "Ahrent", "Aicha",
        "Aida", "Aies", "Aiko", "Aila", "Aili", "Aima", "Aimas", "Aimèe", "Aimi", "Aimy", "Aina", "Aino", "Aisha", "Aishah",
        "Ajatsa", "Ajes", "Akeleje", "Akim", "Akita", "Aksel", "Akseline", "Aksinja", "Akton", "Aladdin", "Alaia", "Alain",
        "Alaine", "Alan", "Alba", "Alban", "Albert", "Alberta", "Alberte", "Alberth", "Albertha", "Alberthine", "Albertina",
        "Albertine", "Alberto", "Albertus", "Albin", "Albina", "Albine", "Albinus", "Albrecht", "Albrekt", "Albret", "Aldo",
        "Alec ", "Aleia", "Alek", "Aleks", "Aleksandar", "Aleksander", "Aleksandra", "Aleksandrine", "Aleksej", "Aleksia",
        "Alessandra", "Aleta", "Alett", "Alette", "Alex", "Alexa", "Alexandar", "Alexander", "Alexandra", "Alexandrina",
        "Alexandrine", "Alexia", "Alexie", "Alexis", "Alexius", "Alfa", "Alfhild", "Alfred", "Alfrede", "Alfrida", "Alfride",
        "Alfrieda", "Alfriede", "Algea", "Alger", "Algot", "Algoth", "Algy", "Alia", "Alice", "Alicia", "Alida", "Aliena",
        "Alikka", "Alina", "Aline", "Alis", "Alisa", "Alise", "Alison", "Alita", "Alitha", "Alitta", "Alitza", "Aliz",
        "Allaine", "Allan", "Allen", "Allette", "Allice", "Allie", "Allis", "Ally", "Allydia", "Alma", "Almar", "Almer",
        "Almine", "Alois", "Aloisia", "Alona", "Aloysius", "Alryda", "Alva", "Alvar", "Alver", "Alvild", "Alvilda", "Alvilde",
        "Alvin", "Alvina", "Alvine", "Alvira", "Alwine", "Amadeus", "Amalia", "Amalie", "Amand", "Amanda", "Amandus",
        "Ambjørn", "Ambrosia", "Ambrosius", "Amdi", "Amelia", "Amelie", "Amélie", "Amilia", "Amilla", "Amina", "Aminah",
        "Amine", "Amira", "Ammund", "Amola", "Amund", "Anastaja", "Anastasia", "Anastasija", "Anastasja", "Anastassia",
        "Anastazia", "Anatol", "Anatole", "Anaya", "Ancher", "Ancia", "Anders", "Andersine", "Andi", "Andras", "Andre",
        "André", "Andrea", "Andreas", "Andrei", "Andrés", "Andrew", "Andrias", "Andriette", "Andrine", "Andry", "Andy", "Anée",
        "Anegrete", "Anegrethe", "Anelise", "Anella", "Anelle", "Anemarie", "Anemette", "Anemone", "Anete", "Anethe", "Anett",
        "Anetta", "Anette", "Anfred", "Angel", "Angela", "Angelica", "Angelie", "Angelika", "Angelina", "Angeline",
        "Angelique", "Angélique", "Angèlique", "Angelita", "Angelo", "Angul", "Angus", "Ania", "Aniara", "Anica", "Anick",
        "Anie", "Aniela", "Aniella", "Aniet", "Anika", "Aniki", "Anilla", "Anina", "Anine", "Aninna", "Anisa", "Anise",
        "Anisette", "Anissa", "Anita", "Anitha", "Anitta", "Anja", "Anjelica", "Anjila", "Anka", "Anke", "Anker", "Ankie",
        "Anli", "Anline", "Anna", "Annabell", "Annabella", "Annabelle", "Annabeth", "Annagrete", "Annagrethe", "Annakarin",
        "Annali", "Annaline", "Annalis", "Annalisa", "Annalise", "Annamarie", "Annamay", "Annamette", "Annamie", "Annasofie",
        "Annastasia", "Annbeth", "Annbrit", "Annbritt", "Anne", "Annebell", "Annebelle", "Annebet", "Annebeth", "Annebirgitte",
        "Annegitte", "Annegrete", "Annegrethe", "Anneke", "Anneken", "Annelene", "Anneli", "Annelie", "Anneliese", "Anneline",
        "Annelis", "Annelisa", "Annelise", "Annelouise", "Annemari", "Annemarie", "Annemette", "Annemie", "Annemona",
        "Annemone", "Annesofie", "Annet", "Annete", "Anneth", "Annethe", "Annett", "Annette", "Anngrethe", "Anni", "Annia",
        "Annica", "Annie", "Annielle", "Annik", "Annika", "Annike", "Annikki", "Annina", "Annine", "Annisette", "Annita",
        "Annitta", "Annizette", "Annli", "Annlil", "Annlisa", "Annlise", "Annmari", "Annmarie", "Annsofi", "Annsofie",
        "Annsophie", "Anny", "Anouk", "Anselm", "Ansgar", "Ansine", "Ante", "Anthon", "Anthonia", "Anthonie", "Anthonio",
        "Anthonius", "Anthony", "Antine", "Antje", "Antoine", "Antoinetta", "Antoinette", "Antomine", "Anton", "Antonella",
        "Antonelle", "Antonette", "Antoni", "Antonia", "Antonie", "Antonina", "Antonine", "Antonio", "Antonius", "Antony",
        "Anya", "Apollo", "Apollus", "Aprilia", "Aqqaluk", "Arabella", "Aram", "Aranka", "Archibald", "Archie", "Arendse",
        "Arendt", "Arense", "Arent", "Ariane", "Arielle", "Arik", "Arild", "Arina", "Arise", "Arkibald", "Arla", "Arlette",
        "Arletty", "Arly", "Armand", "Armin", "Arna", "Arnbjørn", "Arndt", "Arne", "Arnfred", "Arni", "Arnkil", "Arno",
        "Arnold", "Arnt", "Arnth", "Aron", "Arrild", "Arthur", "Artur", "Arved", "Arvid", "Asbjørn", "Asdis", "Asfred",
        "Asfrid", "Asgar", "Asger", "Asgerd", "Ashley", "Asja", "Aske", "Asker", "Askil", "Askild", "Asla", "Aslak", "Aslaug",
        "Asløg", "Asmind", "Asmine", "Asmira", "Asmund", "Asmus", "Asra", "Asser", "Assi", "Assia", "Assika", "Asta", "Asthor",
        "Astor", "Astrid", "Atalia", "Atalie", "Athalia", "Athalie", "Athena", "Athene", "Athina", "Atlanta", "Atle", "Atli",
        "Atos", "Atte", "Attila", "Audrey", "Audun", "Augo", "August", "Augusta", "Auguste", "Augustin", "Augustina",
        "Augustine", "Augustinus", "Augusto", "Augustus", "Aukje", "Aurelia", "Aurica", "Aurora", "Avgusta", "Aviaya", "Axel",
        "Axeline", "Aylil", "Ayma", "Ayna", "Ayoe", "Ayse", "Bagge", "Bahne", "Baki", "Balder", "Baldrian", "Balduin",
        "Baldur", "Balser", "Baltazar", "Balthasar", "Balthazar", "Baltser", "Baltzer", "Balzer", "Bane", "Barnabas", "Barney",
        "Barny", "Barry", "Bart", "Bartel", "Bartholemeus", "Bartholemæus", "Bartholomeus", "Bartolemæus", "Bartolomæus",
        "Bastian", "Behrend", "Behrendt", "Bendiks", "Bendix", "Bendt", "Bendy", "Benedict", "Benedikt", "Bengt", "Benito",
        "Benjamin", "Benn", "Benne", "Bennet", "Benni", "Bennie", "Benno", "Benny", "Benoni", "Bent", "Benth", "Bentt", "Berd",
        "Berend", "Berent", "Berild", "Bernard", "Bernd", "Berndt", "Bernhard", "Bernhardt", "Berni", "Bernino", "Berno",
        "Bernt", "Bernth", "Berny", "Berry", "Bert", "Bertel", "Berthel", "Berthold", "Bertil", "Berto", "Bertold", "Bertolt",
        "Bertram", "Bertrand", "Betino", "Bill", "Billy", "Bing", "Birge", "Birger", "Birk", "Bjarke", "Bjarki", "Bjarne",
        "Bjarni", "Bjarno", "Bjergi", "Bjerke", "Bjerne", "Bjork", "Bjørk", "Bjørke", "Bjørn", "Bjørno", "Blaise", "Blas",
        "Bobbi", "Bobby", "Bode", "Bodo", "Boie", "Boje", "Bonde", "Bone", "Bonne", "Bonnik", "Bonno", "Bonny", "Boris",
        "Borris", "Boyd", "Boye", "Bram", "Brandur", "Brett", "Brian", "Brion", "Broder", "Bror", "Bruce", "Bruno", "Bryan",
        "Bryde", "Brynjolf", "Brynjolfur", "Brynulf", "Bugge", "Buller", "Buris", "Buster", "Buur", "Byrge", "Byrial", "Bøje",
        "Børge", "Børre", "Baard", "Cajus", "Calle", "Calvin", "Camillas", "Camillo", "Carit", "Carl", "Carlis", "Carlo",
        "Carlos", "Carly", "Carsten", "Carter", "Carton", "Caspar", "Casper", "Cassius", "Castello", "Castor", "Cato", "Cecil",
        "Cedric", "Cendy", "Chano", "Charles", "Charley", "Charli", "Charlie", "Charly", "Chester", "Chico", "Chiko", "Chres",
        "Chresten", "Chrestian", "Chrilles", "Chris", "Christen", "Christer", "Christian", "Christiern", "Christof",
        "Christoffer", "Christoph", "Christophe", "Christopher", "Ciano", "Cilas", "Cilius", "Cimmi", "Claes", "Clarence",
        "Clark", "Clas", "Claude", "Claudi", "Claudio", "Claudius", "Claus", "Clavs", "Clemen", "Clemens", "Clement",
        "Clemmen", "Cliff", "Clifford", "Clint", "Clive", "Clyde", "Colin", "Columbus", "Conrad", "Constantin", "Cordt",
        "Corfits", "Corfitz", "Cornelis", "Cornelius", "Cort", "Corty", "Cosmus", "Crilles", "Cris", "Crister", "Cristian",
        "Cristoffer", "Cuno", "Curd", "Curt", "Curtis", "Cyril", "Cyrill", "Cæcilius", "Cæsar", "Daen", "Dagfin", "Dagfinn",
        "Dagh", "Damian", "Dani", "Daniel", "Daniell", "Danilo", "Danjal", "Dann", "Danner", "Danni", "Dannie", "Danny",
        "Dany", "Dargo", "Dario", "Darnell", "Darvin", "Darwin", "Dave", "David", "Davie", "Davy", "Dean", "Denis", "Deniz",
        "Denni", "Dennik", "Dennis", "Denny", "Derek", "Derri", "Derrick", "Derry", "Desmond", "Detlef", "Detlev", "Detmer",
        "Devin", "Dich", "Dick", "Dicky", "Diderich", "Diderik", "Didrich", "Didrik", "Diego", "Dieter", "Dietrich", "Dimitri",
        "Dimitrij", "Dimy", "Dines", "Dinny", "Dino", "Dion", "Dirch", "Dirk", "Ditlef", "Ditlev", "Ditmar", "Ditmer", "Ditz",
        "Dominic", "Donald", "Donni", "Donny", "Douglas", "Dres", "Dreves", "Drevs", "Dusinius", "Dusinus", "Dylan", "Dynes",
        "Earl", "Ebbe", "Ebbi", "Eber", "Eberhard", "Eberhardt", "Echardt", "Eckardt", "Eckhard", "Eckhardt", "Eddi", "Eddy",
        "Edelhard", "Edelhardt", "Edelhart", "Edgar", "Edgard", "Edgardo", "Edlef", "Edmond", "Edmund", "Edouard", "Eduard",
        "Eduardo", "Edvard", "Edvardt", "Edvin", "Edvind", "Edward", "Edwardt", "Edwin", "Efraim", "Egan", "Egbert", "Egert",
        "Eggert", "Egil", "Egild", "Egill", "Egmont", "Egmund", "Egmunt", "Egon", "Egun", "Egund", "Ehler", "Ehlert", "Eide",
        "Eigil", "Eigild", "Eigill", "Eilef", "Eiler", "Eilert", "Eilev", "Eilif", "Einar", "Einer", "Einert", "Eino", "Eirik",
        "Eitel", "Eivin", "Eivind", "Ejgil", "Ejgild", "Ejlar", "Ejlef", "Ejler", "Ejlert", "Ejlev", "Ejlif", "Ejnar", "Ejner",
        "Ejnert", "Ejno", "Ejolf", "Ejvin", "Ejvind", "Ekhard", "Ekhardt", "Elaf", "Elan", "Elav", "Elef", "Elert", "Elfred",
        "Elhardt", "Elias", "Elif", "Elimar", "Eliot", "Elisius", "Elit", "Elith", "Elius", "Elliott", "Elmar", "Elmer",
        "Elmo", "Elmund", "Elof", "Elon", "Elton", "Eluf", "Elvar", "Elvard", "Elver", "Elvin", "Elvind", "Elvinus", "Elvis",
        "Elwin", "Emanuel", "Emiel", "Emil", "Emile", "Emilio", "Emilius", "Emmanuel", "Emmerich", "Emmerik", "Emmert",
        "Emmery", "Emmik", "Emus", "Enevold", "Engelbert", "Engelbrecht", "Engelbrekt", "Engelhard `", "Engelhardt", "Enno",
        "Enoch", "Enok", "Enrico", "Enrique", "Enver", "Enzo", "Erasmus", "Erhard", "Erhardt", "Erhart", "Eric", "Erich",
        "Erick", "Erico", "Erik", "Eriko", "Erin", "Erkki", "Erlan", "Erland", "Erlin", "Erlind", "Erling", "Erly", "Ernest",
        "Ernfred", "Ernhard", "Ernhardt", "Erno", "Ernst", "Eron", "Errit", "Errol", "Ervin", "Ervind", "Erwill", "Erwin",
        "Erwind", "Erwing", "Esaias", "Esajas", "Esben", "Esbern", "Esbjørn", "Esge", "Esger", "Eske", "Eskil", "Eskild",
        "Espen", "Esper", "Ethan", "Etlar", "Eug#Ne", "Eugen", "Eugène", "Evald", "Evan", "Even", "Evert", "Evin", "Evind",
        "Ewald", "Ewan", "Ewert", "Eylef", "Eylev", "Eylif", "Eyolf", "Eyvin", "Eyvind", "Fabian", "Falentin", "Falk", "Falke",
        "Faustin", "Faustino", "Fedder", "Feliks", "Felix", "Feodor", "Ferdinand", "Fernando", "Ferry", "Filip", "Fillip",
        "Find", "Fini", "Finn", "Finni", "Finnur", "Fjodor", "Flemming", "Florian", "Fodor", "Folke", "Folker", "Folkvar",
        "Folkvard", "Folmar", "Folmer", "Francesco", "Franch", "Francis", "Francisco", "Franck", "Francois", "Frands", "Frank",
        "Franker", "Frankie", "Franklin", "Frans", "Fransisco", "Frants", "Frantz", "Franz", "Fred", "Freddi", "Freddie",
        "Freddy", "Frede", "Frederic", "Frédéric", "Frederich", "Frederick", "Frederik", "Fredi", "Fredrik", "Fredy",
        "Freilev", "Freilif", "Frej", "Frejlev", "Frevlif", "Frey", "Fribo", "Fridlev", "Fridolf", "Fridolin", "Fridthjof",
        "Fridtjof", "Friederich", "Friedrich", "Frilo", "Frithiof", "Frithjof", "Fritjof", "Frits", "Fritz", "Frode",
        "Gabriel", "Gary", "Gaston", "Gaute", "Gavin", "Geert", "Geir", "Gejr", "Geno", "Geoffrey", "Georg", "George",
        "Georges", "Georgios", "Gerald", "Geran", "Gerbrand", "Gerdt", "Gerhard", "Gerhardt", "Gerhart", "Gerlak", "Gerland",
        "Gerlef", "Gerluf", "German", "Germann", "Germind", "Germund", "Gerner", "Gerrit", "Gerrith", "Gerry", "Gerson",
        "Gert", "Gerth", "Gerulf", "Gervind", "Gian", "Giancarlo", "Gianni", "Giannino", "Gilbert", "Gino", "Giovanni",
        "Giulio", "Giuseppe", "Glen", "Glenn", "Glenny", "Gleve", "Godfred", "Godik", "Godske", "Godtfred", "Godvin", "Gomme",
        "Gordon", "Gorm", "Gotfred", "Gothard", "Gothardt", "Gotlieb", "Gottfred", "Gottfried", "Gotthard", "Gotthardt",
        "Gottlieb", "Gravers", "Graves", "Greg", "Greger", "Gregers", "Gregor", "Gregorius", "Greif", "Grejs", "Gudbjørn",
        "Gudik", "Gudman", "Gudmand", "Gudmar", "Gudmund", "Guido", "Gullak", "Gumme", "Gunder", "Gunnar", "Gunner", "Gunni",
        "Gunnulf", "Guno", "Gunter", "Gunther", "Gunvald", "Gustaf", "Gustav", "Gustave", "Guttorm", "Gynter", "Gynther",
        "Göran", "Gösta", "Gøtz", "Götz", "Hagbard", "Hagbart", "Hagbarth", "Hagen", "Haggi", "Hajo", "Hakki", "Hakon",
        "Haldor", "Haldur", "Halfdan", "Halfred", "Halldor", "Halvard", "Halvdan", "Halvor", "Hamid", "Hamund", "Hannibal",
        "Hanno", "Hans", "Hansmorten", "Harald", "Harding", "Hardy", "Harley", "Harly", "Harold", "Harri", "Harris", "Harro",
        "Harry", "Hartvig", "Hartwig", "Hasan", "Hassan", "Hasse", "Hassi", "Hauge", "Havard", "Hector", "Hegen", "Hegn",
        "Heikki", "Heiko", "Heile", "Heimer", "Hein", "Heine", "Heiner", "Heines", "Heini", "Heinike", "Heino", "Heinrich",
        "Heinrick", "Heinrik", "Heins", "Heintje", "Heinz", "Heise", "Hejne", "Hektor", "Helfred", "Helge", "Helgi", "Helgo",
        "Hellmut", "Hellmuth", "Helman", "Helmar", "Helmer", "Helmut", "Helmuth", "Hemming", "Hendrik", "Henning", "Henri",
        "Henrich", "Henrik", "Henry", "Herbert", "Heri", "Herluf", "Herman", "Hermann", "Hermod", "Herold", "Hervard",
        "Hieronimus", "Hieronymus", "Hilbert", "Hildebrand", "Hilding", "Hilmar", "Hilmer", "Hjalmar", "Hjalmer", "Hjalte",
        "Hjarn", "Hjarne", "Hoder", "Hold", "Holger", "Holm", "Holme", "Horst", "Hother", "Hovard", "Howard", "Hroar", "Hrolf",
        "Hubert", "Hugh", "Hugi", "Hugin", "Hugo", "Humphrey", "Høgne", "Hågen", "Haagen", "Håkon", "Haakon", "Håvard",
        "Haavard", "Ibrahim", "Ignatius", "Ignazio", "Igor", "Imanuel", "Immanuel", "Imran", "Ingbert", "Ingeman", "Ingemann",
        "Ingemar", "Ingemund", "Ingevald", "Ingi", "Ingmar", "Ingmund", "Ingo", "Ingolf", "Ingvald", "Ingvar", "Ingvard",
        "Ingvardt", "Ingvart", "Ingver", "Ingvert", "Ingvor", "Ioannis", "Irving", "Irwing", "Isaac", "Isac", "Isak",
        "Isegrim", "Isidor", "Istvan", "Ivan", "Ivar", "Iver", "Iwan", "Iwar", "Iwer", "Iørgen", "Jachim", "Jack", "Jackie",
        "Jacko", "Jacky", "Jacob", "Jacques", "Jafet", "Jahn", "Jaime", "Jais", "Jakob", "Jall", "Jalte", "Jamal", "James",
        "Janech", "Janek", "Janich", "Janick", "Jann", "Jannek", "Jannic", "Jannich", "Jannick", "Jannik", "Jannis", "Jano",
        "Janos", "Jansi", "Janus", "Jappe", "Jari", "Jaris", "Jarl", "Jarle", "Jarne", "Jarnik", "Jarnis", "Jarno", "Jaron",
        "Jason", "Jasper", "Jean", "Jeff", "Jeffi", "Jeffrey", "Jeffy", "Jegor", "Jegvan", "Jeko", "Jens", "Jeppe", "Jeremias",
        "Jeremy", "Jerik", "Jerk", "Jerome", "Jeronimus", "Jerri", "Jerrik", "Jerry", "Jesper", "Jess", "Jesse", "Jimi",
        "Jimm", "Jimmi", "Jimmy", "Joachim", "Joacim", "Joah", "Joakim", "Jochum", "Jock", "Joel", "Joël", "Joen", "Johan",
        "Johann", "Johannes", "John", "Johni", "Johnni", "Johnny", "Johny", "Johs", "Jokum", "Jonas", "Jonatan", "Jonathan",
        "Jonny", "Joos", "Joram", "Joran", "Jordy", "Jorge", "Jorn", "Jorry", "Jorst", "José", "Josef", "Joseph", "Josh",
        "Joshua", "Joshva", "Josiah", "Josias", "Jost", "Josua", "Josva", "Jovan", "Jozef", "Juan", "Jules", "Julian",
        "Julius", "Juri", "Jussi", "Just", "Justian", "Justin", "Justus", "Jøgvan", "Jøren", "Jørg", "Jørgen", "Jørk",
        "Jørlief", "Jørn", "Jaan", "Kain", "Kaino", "Kaleb", "Kali", "Kalle", "Kamillo", "Kamo", "Karel", "Kari", "Karim",
        "Karl", "Karle", "Karlis", "Karljohan", "Karlo", "Karnis", "Karno", "Karol", "Karolus", "Karsten", "Kasimir", "Kasmir",
        "Kaspar", "Kasper", "Kastor", "Kean", "Keen", "Kees", "Keith", "Keld", "Kell", "Kelli", "Kelly", "Kelvin", "Kemal",
        "Kenan", "Kenian", "Kenn", "Kennart", "Kennert", "Kennerth", "Kennet", "Kenneth", "Kennett", "Kenney", "Kenni",
        "Kennith", "Kenno", "Kenny", "Kent", "Kenth", "Kento", "Kenwin", "Kermit", "Kern", "Kerner", "Ketel", "Ketil", "Kevin",
        "Kevyn", "Kewan", "Kewin", "Kian", "Kield", "Kiljon", "Killian", "Kimm", "Kimmo", "Kimmy", "Kimo", "Kinn", "Kion",
        "Kirstein", "Kirstejn", "Kito", "Kivin", "Kiwin", "Kjartan", "Kjeld", "Kjell", "Kjertan", "Klaes", "Klas", "Klaudi",
        "Klaudius", "Klaus", "Klaves", "Klavs", "Klemen", "Klemens", "Klement", "Klemmen", "Knud", "Knut", "Kolbjørn",
        "Konrad", "Konstantin", "Kord", "Kore", "Korfits", "Korfitz", "Kornelius", "Kort", "Kosmus", "Krei", "Kren", "Kresten",
        "Krester", "Krestian", "Krestoffer", "Krilles", "Kris", "Kristen", "Krister", "Kristian", "Kristjan", "Kristof",
        "Kristofer", "Kristoffer", "Kræn", "Kræsten", "Krøj", "Kuan", "Kuno", "Kunz", "Kurd", "Kurt", "Kurth", "Kåre", "Kaare",
        "Lage", "Lambert", "Lance", "Landry", "Lanni", "Lari", "Larry", "Lars", "Lasarus", "Lass", "Lasse", "Laue", "Lauge",
        "Launy", "Laurens", "Laurentius", "Lauri", "Laurids", "Laurits", "Lauritz", "Laurs", "Laus", "Laust", "Lavard", "Lave",
        "Lavrids", "Lavrits", "Lavritz", "Lavrs", "Lavst", "Lean", "Leander", "Leck", "Legart", "Leib", "Leif", "Leiff",
        "Lejf", "Lejff", "Lemmy", "Lenarth", "Lennard", "Lennart", "Lennarth", "Lennert", "Lenni", "Lennon", "Lenny", "Leon",
        "Leonard", "Leonhard", "Leonhardt", "Leonhart", "Leopold", "Leslie", "Lester", "Levi", "Levy", "Lewi", "Liam", "Lindy",
        "Linus", "Lionel", "Lorens", "Lorents", "Lorentz", "Lorentzo", "Lorenz", "Lorenzo", "Lorry", "Lothar", "Loui", "Louie",
        "Louis", "Lucas", "Lucien", "Ludolf", "Ludolph", "Ludvig", "Ludwig", "Ludwik", "Luis", "Lukas", "Luke", "Lyder",
        "Lydolf", "Lynge", "Mack", "Mads", "Magal", "Magne", "Magni", "Magnus", "Mahmoud", "Mahmud", "Majid", "Maks",
        "Malakias", "Malcolm", "Malte", "Malthe", "Manderup", "Mandrup", "Manfred", "Manly", "Manne", "Manneke", "Mannfred",
        "Manuel", "Marc", "Marcel", "Marcelius", "Marcell", "Marcello", "Marchel", "Marck", "Marco", "Marcos", "Marcus",
        "Mariano", "Marinus", "Mario", "Marius", "Mark", "Markild", "Marko", "Markus", "Markvar", "Markvard", "Marni", "Marno",
        "Marthen", "Marthin", "Marthinus", "Marti", "Martin", "Martinez", "Martinius", "Martinus", "Martti", "Marty", "Marvin",
        "Marx", "Mass", "Massimo", "Matfus", "Mathfus", "Mathias", "Mathies", "Mathinus", "Mathis", "Matias", "Matis", "Mats",
        "Matt", "Matthes", "Matthfus", "Matthias", "Matthies", "Matthis", "Matthæus", "Matti", "Mattias", "Mattis", "Matts",
        "Mattæus", "Matæus", "Mauri", "Maurice", "Maurits", "Mauritz", "Maxim", "Maxime", "Maximilian", "Maximillian", "Meck",
        "Meik", "Meikey", "Meiner", "Meinert", "Meinhard", "Meino", "Meir", "Mejner", "Mejnert", "Melchior", "Melkior",
        "Melvin", "Meno", "Merlan", "Micael", "Micas", "Mich", "Michael", "Michaell", "Michal", "Michel", "Michell", "Michlas",
        "Mick", "Mickei", "Mickey", "Micki", "Micklas", "Micky", "Mico", "Miguel", "Mihail", "Mikael", "Mikal", "Mike",
        "Mikelis", "Mikey", "Miki", "Mikk", "Mikkel", "Mikki", "Mikko", "Mikllas", "Miklos", "Milan", "Milius", "Millo",
        "Milo", "Milos", "Milter", "Milton", "Mingo", "Minik", "Mirko", "Miro", "Mitchell", "Mogens", "Mohamed", "Molte",
        "Momme", "Monne", "Monty", "Morgan", "Morits", "Moritz", "Morten", "Morthen", "Mortimer", "Morton", "Moses", "Mourids",
        "Mourits", "Mouritz", "Moust", "Muhammad", "Mylius", "Mårten", "Napoleon", "Natan", "Natanael", "Nataniel", "Nathan",
        "Nathanael", "Nathaniel", "Neal", "Neil", "Nelas", "Nels", "Nevil", "Neville", "Niall", "Nichi", "Nichlas", "Nicholai",
        "Nicholaj", "Nicholas", "Nici", "Nick", "Nicki", "Nicklas", "Nicklaus", "Nicklavs", "Nicko", "Nickolai", "Nickolaj",
        "Nickolass", "Nickolei", "Nicky", "Niclas", "Nico", "Nicodemus", "Nicol", "Nicolai", "Nicolaj", "Nicolas", "Nicolaus",
        "Nicolay", "Nicolei", "Nicolej", "Nicolo", "Niel", "Niels", "Nigel", "Nikas", "Nikhil", "Niki", "Nikki", "Niklas",
        "Niklaus", "Niko", "Nikolai", "Nikolaj", "Nikolas", "Nikolaus", "Nikolej", "Nilas", "Nilaus", "Nilavs", "Nils", "Nino",
        "Niss", "Nivan", "Njal", "Noah", "Noal", "Noel", "Noël", "Norbert", "Norman", "Normann", "Obert", "Octavio",
        "Octavius", "Oddvar", "Odger", "Odin", "Odlev", "Odmar", "Odsten", "Olaf", "Olai", "Olaj", "Olander", "Olau", "Olaus",
        "Olav", "Olavur", "Oleg", "Olen", "Olfert", "Oliver", "Olle", "Olof", "Olov", "Oluf", "Omar", "Orla", "Orlando",
        "Oscar", "Oskar", "Osman", "Osmann", "Osmar", "Osmund", "Ossian", "Osvald", "Oswald", "Othar", "Othmar", "Otmann",
        "Otmar", "Ottar", "Otte", "Otto", "Ovard", "Owen", "Oyvind", "Paavo", "Pablo", "Paco", "Paick", "Paie", "Pall",
        "Palle", "Palmer", "Parly", "Parmo", "Pascal", "Patrich", "Patrick", "Patrik", "Pauel", "Paul", "Pauli", "Paulli",
        "Paulo", "Paulus", "Pawel", "Peder", "Pedro", "Peer", "Pehr", "Peik", "Peiter", "Pejk", "Pele", "Pelle", "Penti",
        "Pentti", "Percy", "Perry", "Pete", "Peter", "Petri", "Petro", "Petrus", "Petter", "Philip", "Philippe", "Phillip",
        "Pierre", "Piet", "Pieter", "Pietro", "Piotr", "Pitter", "Pius", "Pouel", "Poul", "Pouli", "Poulus", "Povel", "Povl",
        "Preben", "Predbjørn", "Prosper", "Quintus", "Qvan", "Qvintus", "Racid", "Radolf", "Radulf", "Rafael", "Ragn",
        "Ragnar", "Ragner", "Ragnvald", "Raimo", "Raimond", "Raimund", "Rainar", "Rainer", "Raini", "Rainier", "Raki", "Ralf",
        "Ralff", "Ralph", "Rami", "Ramon", "Randolf", "Randolph", "Randy", "Rane", "Ranulf", "Raphael", "Rasmus", "Rass",
        "Raul", "Rauno", "Ravn", "Raymond", "Raymund", "Rayner", "Regin", "Reginald", "Regnar", "Regner", "Regnvald",
        "Reichard", "Reidar", "Reider", "Reier", "Reimar", "Reimer", "Reimert", "Reimond", "Reinar", "Reiner", "Reinert",
        "Reinhard", "Reinhardt", "Reinhold", "Reinholdt", "Reinholt", "Reino", "Reinold", "Reinvald", "Rejer", "Rejmar",
        "Rejmer", "Rejnar", "Rejner", "Rejnert", "Rejnhard", "Rejnhardt", "Rejnhart", "Rejnhold", "Rejnholdt", "Rejnholt",
        "Remi", "Remo", "Remon", "Remond", "Remus", "Remy", "Renato", "Renatus", "Rene", "Rennie", "Renny", "Reno", "Reto",
        "Reymond", "Reynold", "Riber", "Ricard", "Ricardo", "Ricardt", "Ricco", "Richard", "Richardo", "Richardt", "Richart",
        "Richo", "Rickard", "Rickey", "Ricki", "Rickie", "Ricko", "Ricky", "Rico", "Rief", "Riff", "Rigo", "Rikard", "Rikardt",
        "Rikki", "Rikko", "Riko", "Rino", "Roald", "Roall", "Roan", "Roar", "Robbert", "Robbi", "Robbin", "Robby", "Robert",
        "Roberto", "Robin", "Rocco", "Rocko", "Rocky", "Roer", "Roger", "Rogert", "Rokil", "Roland", "Rolf", "Rolff", "Rollo",
        "Rom-O", "Roman", "Romann", "Romano", "Romanus", "Romeo", "Roméo", "Ronald", "Ronaldo", "Rone", "Ronn", "Ronni",
        "Ronnie", "Ronny", "Rousdi", "Royni", "Ruar", "Ruben", "Rubert", "Ruddi", "Ruddy", "Rudi", "Rudolf", "Rudolph", "Rudy",
        "Rufus", "Rukan", "Rumle", "Runar", "Rune", "Runi", "Runo", "Rupert", "Rurik", "Rustan", "Ryan", "Ryolf", "Sacho",
        "Sakarias", "Sakse", "Sakso", "Salomon", "Salum", "Salvatore", "Sammi", "Sammy", "Samo", "Samson", "Samuel", "Sander",
        "Sandi", "Sandor", "Sandro", "Sandy", "Sanny", "Santino", "Sarino", "Sasser", "Saxe", "Saxo", "Scott", "Sean",
        "Sebald", "Sebastian", "Sebbe", "Seier", "Seir", "Sejer", "Sejner", "Sejr", "Sekstus", "Selgen", "Selius", "Selmar",
        "Selmer", "Semmy", "Senius", "Sennik", "Sepp", "Seppo", "Serge", "Sergei", "Seth", "Sevald", "Sevart", "Severin",
        "Sextus", "Sfmund", "Shahid", "Shane", "Shaun", "Shawn", "Sidney", "Siegfrid", "Siegfried", "Siegmund", "Sievert",
        "Sigbert", "Sigbjørn", "Sigbrand", "Sigbrandt", "Siger", "Sigfred", "Sigfrid", "Sigfried", "Sigfus", "Sigge", "Sigger",
        "Siggi", "Sigismund", "Sigmund", "Sigtryg", "Sigurd", "Sigurt", "Sigvald", "Sigvard", "Sigvardt", "Sigvart", "Sikker",
        "Sikstus", "Silas", "Siliam", "Silius", "Sillas", "Simen", "Simeon", "Simion", "Simoen", "Simon", "Sinius", "Sinus",
        "Sivald", "Sivart", "Sivel", "Sivert", "Sixten", "Sixtus", "Skafte", "Skanni", "Skanny", "Skat", "Skjalm", "Skjold",
        "Skuli", "Snorre", "Snorri", "Sofus", "Sonni", "Sonnich", "Sonny", "Sophus", "Staffan", "Staffen", "Stan", "Stanislau",
        "Stanislav", "Stanislaw", "Stanley", "Stanly", "Stanny", "Steen", "Stefan", "Stefano", "Steff", "Steffan", "Steffen",
        "Steinar", "Steinbjørn", "Stellan", "Sten", "Stener", "Stephan", "Stephen", "Stevan", "Steve", "Steven", "Stig",
        "Stiig", "Stinus", "Stiven", "Stone", "Strange", "Stuart", "Stubbe", "Sture", "Sune", "Suni", "Svante", "Svein",
        "Sveinn", "Sven", "Svend", "Svende", "Svenege", "Svenn", "Svenne", "Svenning", "Svenåge", "Svenaage", "Sverke",
        "Sverkel", "Sverre", "Sverri", "Sylvest", "Sylvester", "Syrach", "Syrak", "Sæmund", "Sølver", "Sønnich", "Sønnik",
        "Søren", "Sørinus", "Tade", "Tage", "Tago", "Taico", "Tais", "Tajco", "Tajs", "Tamas", "Tammes", "Tano", "Tapio",
        "Tarben", "Tarek", "Tarik", "Taus", "Tave", "Tavs", "Teddi", "Teddy", "Teis", "Teit", "Tejn", "Tejs", "Temme", "Temmi",
        "Teobald", "Teodor", "Terje", "Terkel", "Terkil", "Terkild", "Terman", "Termann", "Terri", "Terry", "Teys", "Thadæus",
        "Thage", "Thais", "Tharben", "Theis", "Theiss", "Thejs", "Them", "Theo", "Theobald", "Theodor", "Theon", "Therkel",
        "Therkil", "Therkild", "Therman", "Thim", "Thimotheus", "Thinus", "Thio", "Thoke", "Thom", "Thomas", "Thommas",
        "Thommy", "Thonny", "Thony", "Thor", "Thorald", "Thoralf", "Thorben", "Thorbjørn", "Thord", "Thore", "Thorer",
        "Thorfin", "Thorfinn", "Thorgny", "Thorgot", "Thorgrim", "Thorkel", "Thorkil", "Thorkild", "Thorlak", "Thorleif",
        "Thorlejf", "Thorlejv", "Thorlek", "Thormod", "Thormund", "Thorolf", "Thorstein", "Thorsteinn", "Thorsten", "Thorulf",
        "Thorvald", "Thorvil", "Thorvild", "Thorwald", "Thue", "Thune", "Thure", "Thyge", "Thøge", "Thøger", "Tias", "Tibor",
        "Ticho", "Till", "Tilo", "Timm", "Timme", "Timmi", "Timmo", "Timmy", "Timo", "Timoteus", "Timothy", "Tinny", "Tino",
        "Tinus", "Tito", "Tjalfe", "Tjelle", "Tjørk", "Tjørn", "Tobby", "Tobias", "Toby", "Togi", "Toivo", "Toke", "Toki",
        "Tolvar", "Tolver", "Tomas", "Tomasz", "Tomm", "Tommas", "Tommi", "Tommy", "Tonnes", "Tonni", "Tonnis", "Tonny",
        "Tony", "Toralf", "Torben", "Torbjørn", "Tord", "Tordur", "Tore", "Torfin", "Torfinn", "Torgni", "Torgny", "Torgot",
        "Torgrim", "Torin", "Torjus", "Torke", "Torkel", "Torkil", "Torkild", "Torlak", "Torleif", "Torlek", "Torlif", "Torm",
        "Tormod", "Torre", "Torry", "Torstein", "Torsteinn", "Torsten", "Torulf", "Torvald", "Torvil", "Torvild", "Torvind",
        "Toste", "Tristan", "Troels", "Trohn", "Trond", "Truels", "Truls", "Trygve", "Trym", "Tuco", "Tume", "Tune", "Ture",
        "Turf", "Turmund", "Tycho", "Tyge", "Tøger", "Tønnes", "Tørk", "Ubbe", "Uffe", "Uffo", "Ulfbjørn", "Ulff", "Ulric",
        "Ulrich", "Ulrick", "Ulrik", "Ulver", "Unne", "Urban", "Vaclav", "Vagn", "Vagnar", "Vagner", "Vaino", "Valdemar",
        "Valder", "Valdo", "Valdus", "Valentin", "Valfred", "Valfrid", "Valter", "Valther", "Vandy", "Varny", "Veijo",
        "Veikko", "Venzel", "Vermund", "Verner", "Vernon", "Vesti", "Vesty", "Vicente", "Victor", "Vidar", "Vidrik", "Vifil",
        "Vigan", "Vigand", "Vigandt", "Vigant", "Vigfus", "Vigge", "Viggo", "Vigil", "Viking", "Viktor", "Vilars", "Vilbert",
        "Vildfred", "Vilfred", "Vilhelm", "Villads", "Villars", "Villi", "Villiam", "Villum", "Villy", "Vilmar", "Vilmer",
        "Vilni", "Vincens", "Vincent", "Vinfred", "Virgil", "Virtus", "Viste", "Visti", "Vithar", "Vithard", "Vithardt",
        "Vithus", "Vito", "Vittus", "Vitus", "Vladimir", "Volmar", "Volmer", "Våge", "Vaage", "Waclaw", "Wagn", "Wagner",
        "Wahid", "Waldemar", "Walder", "Walentin", "Walenty", "Walid", "Walter", "Walther", "Wandy", "Warny", "Wenzel",
        "Werner", "Wernon", "Wictor", "Widrik", "Wigan", "Wiggo", "Wiktor", "Wilbert", "Wildfred", "Wilfred", "Wilfried",
        "Wilhelm", "Willads", "Willem", "Willi", "William", "Willum", "Willy", "Wilmar", "Wilmer", "Winn", "Wisti", "Witte",
        "Wladimir", "Wladislaw", "Wladyslaw", "Wolfgang", "Wolmer", "Wåge", "Waage", "Xenius", "Yann", "Yannick", "Yannik",
        "Yngvar", "Yngvard", "Yngve", "Younes", "Yuri", "Yvan", "Yves", "Zacharias", "Zakarias", "Zaki", "Zanno", "Zapp",
        "Zean", "Zenius", "Zeth", "Ziad", "Zier", "Zilas", "Zimon", "Zoltan", "Zoran", "Zygmund", "Øivind", "Øjvind", "Ørni",
        "Ørnulf", "Øssur", "Østen", "Øvli", "Øystein", "Øyvind", "Åbjørn", "Aabjørn", "Aage", "Åmund", "Aamund", "Aaron",
        "Åsmund", "Aasmund", "Abbelone", "Abbie", "Abeline", "Abelone", "Abigael", "Abigail", "Achena")


/**
 * The purpose of Address is to represent simple Addresses
 * @author kasper
 */
data class Address(val address: String, val zip: String, val city: String)


/**
 * The purpose of this class is to be generate random Address objects
 * @author kasper
 */
object AddressGenerator {


    @JvmOverloads
    fun address(maxStreetNr: Int = 100): Address {
        val rnd = Random()
        var street = STREET_NAMES[rnd.nextInt(STREET_NAMES.size)]
        val nr = rnd.nextInt(maxStreetNr) + 1
        street = "$street $nr"
        val cityIndex = rnd.nextInt(ZIP_CITY.size / 2)
        val zip = ZIP_CITY[cityIndex * 2]
        val city = ZIP_CITY[cityIndex * 2 + 1]
        return Address(street, zip, city)
    }
}

private val STREET_NAMES = arrayOf(
        "A.C. Meyers Vænge",
        "Alliancevej",
        "Bavnehøj Alle",
        "Beethovensvej",
        "Belvederekaj",
        "Ben Websters Vej",
        "Blushøjvej",
        "Borgbjergsvej",
        "Borgmester Christiansens Gade",
        "Bådehavnsgade",
        "Cylindervej",
        "Damagervej",
        "Dexter Gordons Vej",
        "Dieselvej",
        "Edvard Storms Vej",
        "Ellebjergvej",
        "Ellestykket",
        "Elværksvej",
        "Enghavevej",
        "Engholmen",
        "Ernie Wilkins Vej",
        "Ernst Kapers Vej",
        "Fiskerihavnsgade",
        "Flydedokken",
        "Fragtvej",
        "Frederikskaj",
        "Gamle Vasbygade",
        "Glinkasvej",
        "Glucksvej",
        "Grønrisvej",
        "Gustav Bangs Gade",
        "H.V. Rolsteds Vej",
        "Hammelstrupvej",
        "Handelsvej",
        "Hans Olriks Vej",
        "Harald Jensens Gade",
        "Havneholmen",
        "Haydnsvej",
        "Hørdumsgade",
        "Johan Kellers Vej",
        "Julius Andersens Vej",
        "K.M. Klausens Gade",
        "Kenny Drews Vej",
        "Kulvej",
        "Landvindingsgade",
        "Lone Kellermanns Vej",
        "Louis Pios Gade",
        "Molestien",
        "Mozarts Plads",
        "Mozartsvej",
        "Natalie Zahles Vej",
        "Nordre Teglkaj",
        "Offenbachsvej",
        "Oscar Pettifords Vej",
        "Otto Brandenburgs Vej",
        "Otto Busses Vej",
        "P. Knudsens Gade",
        "Parkstien",
        "Peter Holms Vej",
        "Peter Sabroes Gade",
        "Pilestykket",
        "Pladehals Allé",
        "Poppelstykket",
        "Rektorparken",
        "Richard Boones Vej",
        "Rossinisvej",
        "Rubinsteinsvej",
        "Scandiagade",
        "Schubertsvej",
        "Sejlklubvej",
        "Sigvald Olsens Gade",
        "Sjællandsbroen",
        "Sjælør Boulevard",
        "Skibbroen",
        "Sluseholmen",
        "Speditørvej",
        "Spontinisvej",
        "Stradellasvej",
        "Straussvej",
        "Stubmøllevej",
        "Støbegodsvej",
        "Støberigade",
        "Sydbanestien",
        "Sydhavns Plads",
        "Sydhavnsgade",
        "Sydløbsvej",
        "Tartinisvej",
        "Teglholm Allé",
        "Teglholm Tværvej",
        "Teglholmens Østkaj",
        "Teglholmsgade",
        "Thad Jones Vej",
        "Thomas Koppels Allé",
        "Tjæregade",
        "Topstykket",
        "Tranehavegård",
        "Tranehavevej",
        "Tudsemindevej",
        "Tømmergravsgade",
        "Unavngiven Vej 1 Uv",
        "V.A. Borgens Vej",
        "Vasbygade",
        "Ved Stigbordene",
        "Vestre Kirkegårds Allé",
        "Vestre Teglgade",
        "Vigerslev Alle",
        "Wagnersvej",
        "Wiinbladsgade",
        "Østre Teglgade",
        "A.F. Kriegers Vej",
        "A.L. Drewsens Vej",
        "Abildgaardsgade",
        "Aggersborggade",
        "Aldersrogade",
        "Amerika Plads",
        "Annekegade",
        "Arendalsgade",
        "Askøgade",
        "Assensgade",
        "Australiensvej",
        "Bechgaardsgade",
        "Bellmans Plads",
        "Bellmansgade",
        "Bergensgade",
        "Berggreensgade",
        "Biskop Krags Vænge",
        "Blegdamsvej",
        "Bogensegade",
        "Bolandsvej",
        "Bomhusvej",
        "Borgervænget",
        "Borgmester Jensens Allé",
        "Borthigsgade",
        "Brammingegade",
        "Bredelandsvej",
        "Brumleby",
        "Bryggergade",
        "Bryggervangen",
        "Bøllemosegårdsvej",
        "Børskovvej",
        "Carl Johans Gade",
        "Carl Nielsens Allé",
        "Christiansmindevej",
        "Classensgade",
        "Collinsgade",
        "Dag Hammarskjölds Allé",
        "Dampfærgevej",
        "Danstrupvej",
        "Drejøgade",
        "Eckersbergsgade",
        "Edel Sauntes Allé",
        "Edvard Griegs Gade",
        "Egebæksvej",
        "Emblasgade",
        "Emdrup Banke",
        "Emdrup Huse",
        "Emdrup Vænge",
        "Emdrupvej",
        "Engelstedsgade",
        "Engskiftevej",
        "F.F. Ulriks Gade",
        "Fakse Tværgade",
        "Faksegade",
        "Fanøgade",
        "Fiskedamsgade",
        "Folke Bernadottes Allé",
        "Forbindelsesvej",
        "Frederik V's Vej",
        "Fridtjof Nansens Plads",
        "Fruebjergvej",
        "Fåborggade",
        "Gammel Kalkbrænderi Vej",
        "Gartnerivej",
        "Gefionsgade",
        "Glænøgade",
        "Grenågade",
        "Gribskovvej",
        "Gunhildsgade",
        "Gunnar Nu Hansens Plads",
        "Gustav Adolfs Gade",
        "Gyritegade",
        "H.C. Lumbyes Gade",
        "H.P. Ørums Gade",
        "Hallinsgade",
        "Halsskovgade",
        "Hammershusgade",
        "Hans Knudsens Plads",
        "Haraldsgade",
        "Hardangergade",
        "Hedemannsgade",
        "Heisesgade",
        "Helgesensgade",
        "Helsingborggade",
        "Henrik Harpestrengs Vej",
        "Herninggade",
        "Hesseløgade",
        "Hf. Borgervænget",
        "Hildursgade",
        "Hjalmar Brantings Plads",
        "Hjelmsgade",
        "Hjortøgade",
        "Hjørringgade",
        "Hobrogade",
        "Holbækgade",
        "Holstebrogade",
        "Holsteinsgade",
        "Hornemansgade",
        "Horsensgade",
        "Horserødvej",
        "Hovgaardsgade",
        "Høyensgade",
        "Indiakaj",
        "Indiavej",
        "Irmingersgade",
        "J.A. Schwartz Gade",
        "J.E. Ohlsens Gade",
        "Jacob Erlandsens Gade",
        "Jagtvej",
        "Jellingegade",
        "Jens Juels Gade",
        "Jens Munks Gade",
        "Johan Svendsens Vej",
        "Juliane Maries Vej",
        "Kalkbrænderihavnsgade",
        "Kalkbrænderiløbskaj",
        "Kanslergade",
        "Kastellet",
        "Kastelsvej",
        "Keldsøvej",
        "Kertemindegade",
        "Kildevældsgade",
        "Kildevænget",
        "Kirsteinsgade",
        "Klosterrisvej",
        "Klostervænget",
        "Klædemålet",
        "Koldinggade",
        "Kong Oscars Gade",
        "Korsørgade",
        "Krausesvej",
        "Kristianiagade",
        "Kristineberg",
        "Kroghsgade",
        "Kuhlausgade",
        "Landskronagade",
        "Langelinie",
        "Langelinie Allé",
        "Langeliniekaj",
        "Lange-Müllers Gade",
        "Langesund",
        "Langøgade",
        "Lautrupsgade",
        "Lautrupskaj",
        "Lersø Parkallé",
        "Lersøstien",
        "Lille Farimagsgade",
        "Lilly Helveg Petersens Plads",
        "Lindenovsgade",
        "Lipkesgade",
        "Livjægergade",
        "Livøgade",
        "Lundehusvej",
        "Lundingsgade",
        "Lundsgade",
        "Lyngbyvej",
        "Løgstørgade",
        "Malmøgade",
        "Mandalsgade",
        "Manøgade",
        "Marmorvej",
        "Marskensgade",
        "Marstalsgade",
        "Marthagade",
        "Masnedøgade",
        "Melchiors Plads",
        "Middelfartgade",
        "Midtermolen",
        "Musholmgade",
        "Møllegårdsvej",
        "Mårumvej",
        "Niels W. Gades Gade",
        "Nordborggade",
        "Nordre Frihavnsgade",
        "Ny Blegdamsvej",
        "Nyborggade",
        "Nygårdsvej",
        "Næstvedgade",
        "Nøjsomhedsvej",
        "Nørre Alle",
        "Odensegade",
        "Oliemøllegade",
        "Olof Palmes Gade",
        "Olufsvej",
        "Omøgade",
        "Oslo Plads",
        "Otto Mallings Gade",
        "Ourøgade",
        "Ove Rodes Plads",
        "Pakhusvej",
        "Per Henrik Lings Allé",
        "Petersborgvej",
        "Præstøgade",
        "Ragnagade",
        "Ragnhildgade",
        "Ramløsevej",
        "Randersgade",
        "Reersøgade",
        "Ribegade",
        "Ringkøbinggade",
        "Ringstedgade",
        "Romsøgade",
        "Rosbæksvej",
        "Rosendalsgade",
        "Rosenvængets Alle",
        "Rosenvængets Hovedvej",
        "Rosenvængets Sideallé",
        "Rothesgade",
        "Rovsingsgade",
        "Rudolph Berghs Gade",
        "Ryesgade",
        "Ryparken",
        "Ryvangs Allé",
        "Rønnegade",
        "Rørsøstien",
        "Samsøgade",
        "Sankt Jakobs Gade",
        "Sankt Jakobs Plads",
        "Sankt Kjelds Gade",
        "Sankt Kjelds Plads",
        "Scherfigsvej",
        "Sejrøgade",
        "Serridslevvej",
        "Sifs Plads",
        "Silkeborg Plads",
        "Silkeborggade",
        "Sionsgade",
        "Skanderborggade",
        "Skarøgade",
        "Skovgaardsgade",
        "Slagelsegade",
        "Soldalen",
        "Solvænget",
        "Sortedam Dossering",
        "Sorøgade",
        "Spangbergsgade",
        "Stadens Vænge",
        "Stakkesund",
        "Stavangergade",
        "Steen Billes Gade",
        "Stockholmsgade",
        "Strandboulevarden",
        "Strandpromenaden",
        "Strandvejen",
        "Strandvænget",
        "Strandøre",
        "Strynøgade",
        "Strødamvej",
        "Stubbeløbgade",
        "Studsgaardsgade",
        "Sundkrogen",
        "Sundkrogsgade",
        "Sundkrogskaj",
        "Svaneknoppen",
        "Svanemøllens Kaserne",
        "Svanemøllevej",
        "Svanevænget",
        "Svendborggade",
        "Sæbygade",
        "Sølundsvej",
        "Sønderborggade",
        "Søpassagen",
        "Saabyesvej",
        "Teglstrupvej",
        "Teglværksgade",
        "Thomas Laubs Gade",
        "Trepkasgade",
        "Trianglen",
        "Trondhjems Plads",
        "Trondhjemsgade",
        "Tåsingegade",
        "Universitetsparken",
        "Upsalagade",
        "Urbansgade",
        "Valdemar Holmers Gade",
        "Vangehusvej",
        "Vardegade",
        "Ved Hegnet",
        "Ved Kildevældskirken",
        "Ved Klosteret",
        "Ved Sporsløjfen",
        "Ved Vænget",
        "Vejlegade",
        "Vejrøgade",
        "Vennemindevej",
        "Venøgade",
        "Vermundsgade",
        "Vestagervej",
        "Vesterled",
        "Vibekegade",
        "Viborggade",
        "Victor Bendix Gade",
        "Victor Borges Plads",
        "Visbygade",
        "Vognmandsmarken",
        "Voldmestergade",
        "Vordingborggade",
        "Webersgade",
        "Weysesgade",
        "Wiedeweltsgade",
        "Wilhelm Marstrands Gade",
        "Willemoesgade",
        "Zinnsgade",
        "Æbeløgade",
        "Østbanegade",
        "Øster Alle",
        "Øster Farimagsgade",
        "Øster Søgade",
        "Østerbrogade",
        "Østerfælled Torv",
        "Østerled",
        "Ålborggade",
        "Århus Plads",
        "Århusgade")

private val ZIP_CITY = arrayOf(
        "5320", " Agedrup",
        "6753", " Agerbæk",
        "6534", " Agerskov",
        "2620", " Albertslund",
        "3450", " Allerød",
        "8961", " Allingåbro",
        "3770", " Allinge",
        "6051", " Almind",
        "8592", " Anholt",
        "8643", " Ans By",
        "6823", " Ansager",
        "9510", " Arden",
        "4792", " Askeby",
        "4550", " Asnæs",
        "5466", " Asperup",
        "5610", " Assens",
        "9340", " Asaa",
        "6440", " Augustenborg",
        "7490", " Aulum",
        "8963", " Auning",
        "5935", " Bagenkop",
        "2880", " Bagsværd",
        "8444", " Balle",
        "2750", " Ballerup",
        "4941", " Bandholm",
        "7150", " Barrit",
        "8330", " Beder",
        "7755", " Bedsted Thy",
        "6541", " Bevtoft",
        "6852", " Billum",
        "7190", " Billund",
        "9881", " Bindslev",
        "3460", " Birkerød",
        "8850", " Bjerringbro",
        "6091", " Bjert",
        "4632", " Bjæverskov",
        "9492", " Blokhus",
        "5491", " Blommenslyst",
        "6857", " Blåvand",
        "4242", " Boeslunde",
        "5400", " Bogense",
        "4793", " Bogø By",
        "6392", " Bolderslev",
        "7441", " Bording",
        "4791", " Borre",
        "4140", " Borup",
        "8220", " Brabrand",
        "6740", " Bramming",
        "7330", " Brande",
        "6535", " Branderup Jylland",
        "6261", " Bredebro",
        "7182", " Bredsten",
        "5464", " Brenderup Fyn",
        "6310", " Broager",
        "5672", " Broby",
        "9460", " Brovst",
        "8654", " Bryrup",
        "8740", " Brædstrup",
        "2605", " Brøndby",
        "2660", " Brøndby Strand",
        "9700", " Brønderslev",
        "2700", " Brønshøj",
        "6650", " Brørup",
        "6372", " Bylderup-Bov",
        "6622", " Bække",
        "7660", " Bækmarksbro",
        "9574", " Bælum",
        "7080", " Børkop",
        "7650", " Bøvlingbjerg",
        "2920", " Charlottenlund",
        "6070", " Christiansfeld",
        "5380", " Dalby",
        "4261", " Dalmose",
        "4983", " Dannemare",
        "8721", " Daugård",
        "4293", " Dianalund",
        "2791", " Dragør",
        "9330", " Dronninglund",
        "3120", " Dronningmølle",
        "9352", " Dybvad",
        "2870", " Dyssegård",
        "5631", " Ebberup",
        "8400", " Ebeltoft",
        "6320", " Egernsund",
        "6040", " Egtved",
        "8250", " Egå",
        "5592", " Ejby",
        "7361", " Ejstrupholm",
        "7442", " Engesvang",
        "4895", " Errindlev",
        "7950", " Erslev",
        "6700", " Esbjerg",
        "6715", " Esbjerg N",
        "6710", " Esbjerg V",
        "6705", " Esbjerg Ø",
        "4593", " Eskebjerg",
        "4863", " Eskilstrup",
        "3060", " Espergærde",
        "4640", " Fakse",
        "4654", " Fakse Ladeplads",
        "6720", " Fanø",
        "9640", " Farsø",
        "3520", " Farum",
        "4944", " Fejø",
        "5863", " Ferritslev Fyn",
        "4173", " Fjenneslev",
        "9690", " Fjerritslev",
        "8762", " Flemming",
        "3480", " Fredensborg",
        "7000", " Fredericia",
        "2000", " Frederiksberg",
        "9900", " Frederikshavn",
        "3600", " Frederikssund",
        "3300", " Frederiksværk",
        "5871", " Frørup",
        "7741", " Frøstrup",
        "4250", " Fuglebjerg",
        "7884", " Fur",
        "4591", " Føllenslev",
        "6683", " Føvling",
        "5600", " Faaborg",
        "4540", " Fårevejle",
        "8990", " Fårup",
        "8882", " Fårvang",
        "7321", " Gadbjerg",
        "4621", " Gadstrup",
        "8464", " Galten",
        "9362", " Gandrup",
        "4874", " Gedser",
        "9631", " Gedsted",
        "8751", " Gedved",
        "5591", " Gelsted",
        "2820", " Gentofte",
        "6621", " Gesten",
        "3250", " Gilleleje",
        "5854", " Gislev",
        "4532", " Gislinge",
        "9260", " Gistrup",
        "7323", " Give",
        "8983", " Gjerlev Jylland",
        "8883", " Gjern",
        "5620", " Glamsbjerg",
        "6752", " Glejbjerg",
        "8585", " Glesborg",
        "2600", " Glostrup",
        "4171", " Glumsø",
        "6510", " Gram",
        "6771", " Gredstedbro",
        "8500", " Grenaa",
        "2670", " Greve",
        "4571", " Grevinge",
        "7200", " Grindsted",
        "3230", " Græsted",
        "6300", " Gråsten",
        "5892", " Gudbjerg Sydfyn",
        "3760", " Gudhjem",
        "5884", " Gudme",
        "4862", " Guldborg",
        "6690", " Gørding",
        "4281", " Gørlev",
        "3330", " Gørløse",
        "6100", " Haderslev",
        "7540", " Haderup",
        "8370", " Hadsten",
        "9560", " Hadsund",
        "9370", " Hals",
        "8450", " Hammel",
        "7362", " Hampen",
        "7730", " Hanstholm",
        "7673", " Harboøre",
        "8462", " Harlev Jylland",
        "5463", " Harndrup",
        "4912", " Harpelunde",
        "3790", " Hasle",
        "4690", " Haslev",
        "8361", " Hasselager",
        "4622", " Havdrup",
        "8970", " Havndal",
        "2640", " Hedehusene",
        "8722", " Hedensted",
        "6094", " Hejls",
        "7250", " Hejnsvig",
        "3150", " Hellebæk",
        "2900", " Hellerup",
        "3200", " Helsinge",
        "3000", " Helsingør",
        "6893", " Hemmet",
        "6854", " Henne",
        "4681", " Herfølge",
        "2730", " Herlev",
        "4160", " Herlufmagle",
        "7400", " Herning",
        "5874", " Hesselager",
        "3400", " Hillerød",
        "8382", " Hinnerup",
        "9850", " Hirtshals",
        "9320", " Hjallerup",
        "7560", " Hjerm",
        "8530", " Hjortshøj",
        "9800", " Hjørring",
        "9500", " Hobro",
        "4300", " Holbæk",
        "4960", " Holeby",
        "4684", " Holmegaard",
        "7500", " Holstebro",
        "6670", " Holsted",
        "2840", " Holte",
        "4871", " Horbelev",
        "3100", " Hornbæk",
        "8543", " Hornslet",
        "8783", " Hornsyld",
        "8700", " Horsens",
        "4913", " Horslunde",
        "6682", " Hovborg",
        "8732", " Hovedgård",
        "5932", " Humble",
        "3050", " Humlebæk",
        "3390", " Hundested",
        "8350", " Hundslund",
        "7760", " Hurup Thy",
        "4330", " Hvalsø",
        "6960", " Hvide Sande",
        "2650", " Hvidovre",
        "8270", " Højbjerg",
        "4573", " Højby",
        "6280", " Højer",
        "7840", " Højslev",
        "4270", " Høng",
        "8362", " Hørning",
        "2970", " Hørsholm",
        "4534", " Hørve",
        "5683", " Haarby",
        "4652", " Hårlev",
        "4872", " Idestrup",
        "7430", " Ikast",
        "2635", " Ishøj",
        "6851", " Janderup Vestjylland",
        "7300", " Jelling",
        "9740", " Jerslev Jylland",
        "4490", " Jerslev Sjælland",
        "9981", " Jerup",
        "6064", " Jordrup",
        "7130", " Juelsminde",
        "4450", " Jyderup",
        "4040", " Jyllinge",
        "4174", " Jystrup Midtsjælland",
        "3630", " Jægerspris",
        "4400", " Kalundborg",
        "4771", " Kalvehave",
        "7960", " Karby",
        "4653", " Karise",
        "2690", " Karlslunde",
        "4736", " Karrebæksminde",
        "7470", " Karup Jylland",
        "2770", " Kastrup",
        "5300", " Kerteminde",
        "4892", " Kettinge",
        "6933", " Kibæk",
        "4360", " Kirke Eskilstrup",
        "4070", " Kirke Hyllinge",
        "4060", " Kirke Såby",
        "8620", " Kjellerup",
        "2930", " Klampenborg",
        "9270", " Klarup",
        "3782", " Klemensker",
        "4672", " Klippinge",
        "8765", " Klovborg",
        "8420", " Knebel",
        "2980", " Kokkedal",
        "6000", " Kolding",
        "8560", " Kolind",
        "2800", " Kongens Lyngby",
        "9293", " Kongerslev",
        "4220", " Korsør",
        "6340", " Kruså",
        "3490", " Kvistgård",
        "5772", " Kværndrup",
        "2200", " København N",
        "2400", " København NV",
        "2300", " København S",
        "2450", " København SV",
        "2100", " København Ø",
        "4600", " Køge",
        "4772", " Langebæk",
        "5550", " Langeskov",
        "8870", " Langå",
        "4320", " Lejre",
        "6940", " Lem St.",
        "8632", " Lemming",
        "7620", " Lemvig",
        "4623", " Lille Skensved",
        "6660", " Lintrup",
        "3360", " Liseleje",
        "4750", " Lundby",
        "6640", " Lunderskov",
        "3540", " Lynge",
        "8520", " Lystrup",
        "9940", " Læsø",
        "8831", " Løgstrup",
        "9670", " Løgstør",
        "6240", " Løgumkloster",
        "9480", " Løkken",
        "8723", " Løsning",
        "8670", " Låsby",
        "8340", " Malling",
        "9550", " Mariager",
        "4930", " Maribo",
        "5290", " Marslev",
        "5960", " Marstal",
        "5390", " Martofte",
        "3370", " Melby",
        "4735", " Mern",
        "5370", " Mesinge",
        "5500", " Middelfart",
        "5642", " Millinge",
        "5462", " Morud",
        "4190", " Munke Bjergby",
        "5330", " Munkebo",
        "9632", " Møldrup",
        "8544", " Mørke",
        "4440", " Mørkøv",
        "2760", " Måløv",
        "8320", " Mårslet",
        "4900", " Nakskov",
        "3730", " Nexø",
        "9240", " Nibe",
        "8581", " Nimtofte",
        "2990", " Nivå",
        "6430", " Nordborg",
        "5800", " Nyborg",
        "4800", " Nykøbing Falster",
        "7900", " Nykøbing Mors",
        "4500", " Nykøbing Sjælland",
        "4296", " Nyrup",
        "4880", " Nysted",
        "2850", " Nærum",
        "4700", " Næstved",
        "9610", " Nørager",
        "4840", " Nørre Alslev",
        "4572", " Nørre Asmindrup",
        "6830", " Nørre Nebel",
        "8766", " Nørre Snede",
        "5580", " Nørre Aaby",
        "4951", " Nørreballe",
        "9400", " Nørresundby",
        "8300", " Odder",
        "5000", " Odense C",
        "5230", " Odense M",
        "5270", " Odense N",
        "5210", " Odense NV",
        "5240", " Odense NØ",
        "5260", " Odense S",
        "5250", " Odense SV",
        "5220", " Odense SØ",
        "5200", " Odense V",
        "6840", " Oksbøl",
        "5450", " Otterup",
        "5883", " Oure",
        "6855", " Ovtrup",
        "6330", " Padborg",
        "9490", " Pandrup",
        "4720", " Præstø",
        "7183", " Randbøl",
        "8900", " Randers",
        "9681", " Ranum",
        "8763", " Rask Mølle",
        "7970", " Redsted Mors",
        "4420", " Regstrup",
        "6760", " Ribe",
        "5750", " Ringe",
        "6950", " Ringkøbing",
        "4100", " Ringsted",
        "8240", " Risskov",
        "4000", " Roskilde",
        "7870", " Roslev",
        "4243", " Rude",
        "5900", " Rudkøbing",
        "4291", " Ruds Vedby",
        "2960", " Rungsted Kyst",
        "8680", " Ry",
        "5350", " Rynkeby",
        "8550", " Ryomgård",
        "5856", " Ryslinge",
        "4970", " Rødby",
        "6630", " Rødding",
        "6230", " Rødekro",
        "8840", " Rødkærsbro",
        "2610", " Rødovre",
        "4673", " Rødvig Stevns",
        "6792", " Rømø",
        "8410", " Rønde",
        "3700", " Rønne",
        "4683", " Rønnede",
        "4581", " Rørvig",
        "8471", " Sabro",
        "4990", " Sakskøbing",
        "9493", " Saltum",
        "8305", " Samsø",
        "4262", " Sandved",
        "4592", " Sejerø",
        "8600", " Silkeborg",
        "9870", " Sindal",
        "4583", " Sjællands Odde",
        "6093", " Sjølund",
        "9990", " Skagen",
        "8832", " Skals",
        "5485", " Skamby",
        "8660", " Skanderborg",
        "4050", " Skibby",
        "7800", " Skive",
        "6900", " Skjern",
        "2942", " Skodsborg",
        "2740", " Skovlunde",
        "4230", " Skælskør",
        "6780", " Skærbæk",
        "3320", " Skævinge",
        "8541", " Skødstrup",
        "9520", " Skørping",
        "5881", " Skårup Fyn",
        "4200", " Slagelse",
        "3550", " Slangerup",
        "2765", " Smørum",
        "7752", " Snedsted",
        "3070", " Snekkersten",
        "4460", " Snertinge",
        "8355", " Solbjerg",
        "2680", " Solrød Strand",
        "6560", " Sommersted",
        "8641", " Sorring",
        "4180", " Sorø",
        "8981", " Spentrup",
        "6971", " Spjald",
        "8472", " Sporup",
        "7860", " Spøttrup",
        "7270", " Stakroge",
        "4780", " Stege",
        "8781", " Stenderup",
        "4295", " Stenlille",
        "3660", " Stenløse",
        "5771", " Stenstrup",
        "4773", " Stensved",
        "7850", " Stoholm Jylland",
        "4952", " Stokkemarke",
        "4480", " Store Fuglede",
        "4660", " Store Heddinge",
        "4370", " Store Merløse",
        "9280", " Storvorde",
        "7140", " Stouby",
        "9970", " Strandby",
        "7600", " Struer",
        "4671", " Strøby",
        "4850", " Stubbekøbing",
        "9530", " Støvring",
        "9541", " Suldrup",
        "9381", " Sulsted",
        "7451", " Sunds",
        "3740", " Svaneke",
        "4470", " Svebølle",
        "5700", " Svendborg",
        "9230", " Svenstrup Jylland",
        "4520", " Svinninge",
        "6470", " Sydals",
        "9300", " Sæby",
        "2860", " Søborg",
        "5985", " Søby Ærø",
        "4920", " Søllested",
        "7280", " Sønder Felding",
        "7260", " Sønder Omme",
        "6092", " Sønder Stenderup",
        "6400", " Sønderborg",
        "5471", " Søndersø",
        "7550", " Sørvad",
        "4733", " Tappernøje",
        "6880", " Tarm",
        "9575", " Terndrup",
        "8653", " Them",
        "7700", " Thisted",
        "8881", " Thorsø",
        "7680", " Thyborøn",
        "7790", " Thyholm",
        "3080", " Tikøb",
        "8381", " Tilst",
        "6980", " Tim",
        "6360", " Tinglev",
        "6862", " Tistrup",
        "3220", " Tisvildeleje",
        "8830", " Tjele",
        "6731", " Tjæreborg",
        "6520", " Toftlund",
        "5690", " Tommerup",
        "4891", " Toreby Lolland",
        "4943", " Torrig Lolland",
        "8310", " Tranbjerg Jylland",
        "5953", " Tranekær",
        "8380", " Trige",
        "8570", " Trustrup",
        "4682", " Tureby",
        "9382", " Tylstrup",
        "4340", " Tølløse",
        "6270", " Tønder",
        "7160", " Tørring",
        "9830", " Tårs",
        "2630", " Taastrup",
        "4350", " Ugerløse",
        "7171", " Uldum",
        "6990", " Ulfborg",
        "5540", " Ullerslev",
        "8860", " Ulstrup",
        "9430", " Vadum",
        "2500", " Valby",
        "2625", " Vallensbæk",
        "2665", " Vallensbæk Strand",
        "6580", " Vamdrup",
        "7184", " Vandel",
        "2720", " Vanløse",
        "6800", " Varde",
        "2950", " Vedbæk",
        "5474", " Veflinge",
        "3210", " Vejby",
        "6600", " Vejen",
        "6853", " Vejers Strand",
        "7100", " Vejle",
        "7120", " Vejle Øst",
        "5882", " Vejstrup",
        "3670", " Veksø Sjælland",
        "7570", " Vemb",
        "4241", " Vemmelev",
        "7742", " Vesløs",
        "9380", " Vestbjerg",
        "5762", " Vester Skerninge",
        "4953", " Vesterborg",
        "7770", " Vestervig",
        "8800", " Viborg",
        "8260", " Viby Jylland",
        "4130", " Viby Sjælland",
        "6920", " Videbæk",
        "4560", " Vig",
        "7480", " Vildbjerg",
        "7980", " Vils",
        "7830", " Vinderup",
        "4390", " Vipperød",
        "2830", " Virum",
        "5492", " Vissenbjerg",
        "6052", " Viuf",
        "9310", " Vodskov",
        "6500", " Vojens",
        "7173", " Vonge",
        "6623", " Vorbasse",
        "4760", " Vordingborg",
        "9760", " Vrå",
        "4873", " Væggerløse",
        "3500", " Værløse",
        "5970", " Ærøskøbing",
        "6870", " Ølgod",
        "3310", " Ølsted",
        "3650", " Ølstykke",
        "5853", " Ørbæk",
        "6973", " Ørnhøj",
        "8950", " Ørsted",
        "8586", " Ørum Djurs",
        "8752", " Østbirk",
        "7990", " Øster Assels",
        "4894", " Øster Ulslev",
        "9750", " Øster Vrå",
        "3751", " Østermarie",
        "6200", " Aabenraa",
        "9440", " Aabybro",
        "8230", " Åbyhøj",
        "3720", " Aakirkeby",
        "9000", " Aalborg",
        "9200", " Aalborg SV",
        "9210", " Aalborg SØ",
        "9220", " Aalborg Øst",
        "9982", " Ålbæk",
        "9620", " Aalestrup",
        "3140", " Ålsgårde",
        "8000", " Århus C",
        "8200", " Århus N",
        "8210", " Århus V",
        "6818", " Årre",
        "9600", " Aars",
        "5792", " Årslev",
        "5560", " Aarup")
